experiment_name: "quantum_byzantine_detection_cifar10"
dataset: "cifar10"

federated:
  num_honest_clients: 15
  num_byzantine_clients: 3
  num_rounds: 30
  local_epochs: 7
  batch_size: 32
  learning_rate: 0.07

quantum:
  num_qubits: 27
  num_shots: 1024
  backend_type: "aer_simulator"
  use_gpu: true
  max_memory_mb: 20000
  batch_size: 3
  feature_map_reps: 2
  entanglement: "full"
  top_k_outcomes: 1000

detection:
  detection_method: "standard_multikrum"
  projection_method: "importance"
  projection_dim: 27
  detection_noise: 0.5
  detection_methods:
    - "standard_multikrum"
    - "classical_random" 
    - "classical_importance"
    - "quantum_zz"
    - "quantum_pauli"
    - "quantum_heisenberg"

attack:
  attack_type: "lie_attack"
  z_max_range: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  attack_strength: 1.0

seed: 42
device: "auto"
log_level: "INFO"
save_results: true
output_dir: "./results"